#!/usr/bin/env python3
"""Download selected public ENA FASTQ files without overwriting payloads.

The input TSV is a provenance artifact generated by the ENA file report. Each
successful download is atomically renamed from a `.partial` path and is later
hash-audited by ``audit_fastq_payload.py``. A failed transfer leaves its
partial file and the failure in the caller's log for diagnosis.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--output-root", required=True, type=Path)
    parser.add_argument("--run", action="append", dest="runs")
    args = parser.parse_args()

    selected = set(args.runs or [])
    with args.manifest.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))
    if not rows:
        raise ValueError("ENA manifest is empty")
    required = {"run_accession", "file_url", "file_name", "file_bytes"}
    missing = required - set(rows[0])
    if missing:
        raise ValueError(f"ENA manifest missing columns: {sorted(missing)}")

    if selected:
        rows = [row for row in rows if row["run_accession"] in selected]
    if not rows:
        raise ValueError("no manifest rows match --run")

    exit_code = 0
    for row in rows:
        run = row["run_accession"]
        destination = args.output_root / run / row["file_name"]
        partial = destination.with_name(destination.name + ".partial")
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.exists():
            observed = sha256(destination)
            print(json.dumps({"status": "EXISTS_NOT_OVERWRITTEN", "run": run, "path": str(destination), "sha256": observed}, sort_keys=True), flush=True)
            continue

        command = [
            "curl",
            "--fail",
            "--location",
            "--retry",
            "8",
            "--retry-delay",
            "5",
            "--retry-all-errors",
            "--connect-timeout",
            "30",
            "--max-time",
            "0",
            "--user-agent",
            "Mozilla/5.0",
            "--referer",
            "https://www.ebi.ac.uk/",
            "--continue-at",
            "-",
            "--output",
            str(partial),
            row["file_url"],
        ]
        print(json.dumps({"status": "START", "run": run, "path": str(destination), "url": row["file_url"], "expected_bytes": row["file_bytes"]}, sort_keys=True), flush=True)
        completed = subprocess.run(command, check=False)
        if completed.returncode != 0:
            exit_code = completed.returncode or 1
            print(json.dumps({"status": "DOWNLOAD_FAILED_PARTIAL_PRESERVED", "run": run, "path": str(partial), "returncode": completed.returncode}, sort_keys=True), flush=True)
            continue
        os.replace(partial, destination)
        observed_size = destination.stat().st_size
        observed_sha256 = sha256(destination)
        print(json.dumps({"status": "DOWNLOADED", "run": run, "path": str(destination), "size_bytes": observed_size, "sha256": observed_sha256}, sort_keys=True), flush=True)

    print(json.dumps({"status": "COMPLETE" if exit_code == 0 else "PARTIAL_FAILURES_PRESERVED", "finished_at_utc": datetime.now(timezone.utc).isoformat(), "exit_code": exit_code}, sort_keys=True), flush=True)
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
